import { type NextPage } from "next";
import Head from "next/head";
import NavBar from "~/components/NavBar";
import Footer from "~/components/Footer";
import HomeHero from "~/components/HomeHero";
import ImageGrid from "~/components/ImageGrid";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hunters for Access</title>
        <meta
          name="description"
          content="Landing page for Montana Hunter's for Access. Promoting and incentivizing Block Management."
        />
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <HomeHero />
        <ImageGrid />
        <Footer />
      </main>
    </>
  );
};

export default Home;
